#!/usr/bin/env node

'use strict'

var c = require('skilstak-colors');

var printHello = function () {
  console.log("Hello World");
}

var printColors = function(){
  console.log(c.rc + "Hello universe");
}

var printOrange = function() {
  console.log(c.multi("Hello Universe")
  while (true){
  printPlain();


