#!/usr/bin/env node

'use strict'

var c = require('skilstak-colors');

var printHello = function () {
  console.log("Hello Waffles");
}

var printForever = function() {
  while (true){
  console.log(c.rc + "Hello Waffles");
}

var printRed = function(message) {
  console.log(c.clear + c.r + "Hello Waffles" + message + c.reset)
}

var printMulti = function (message) {
  while (true) {
    console.log(c.clear + c.multi("Hello Waffles" + message) + c.reset)
  }
}

var name = process.argv[2];

printMulti(name);

//defaults

var name = "Waffles"
var option = "-m";


